// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/25 23:48:09
const configMerger = require("/Users/tangjiashan/Desktop/website/yimei/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/tangjiashan/Desktop/website/yimei/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tangjiashan/Desktop/website/yimei/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tangjiashan/Desktop/website/yimei/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tangjiashan/Desktop/website/yimei/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tangjiashan/Desktop/website/yimei/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tangjiashan/Desktop/website/yimei/plugins/**/*.{js,ts,mjs}","/Users/tangjiashan/Desktop/website/yimei/composables/**/*.{js,ts,mjs}","/Users/tangjiashan/Desktop/website/yimei/utils/**/*.{js,ts,mjs}","/Users/tangjiashan/Desktop/website/yimei/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tangjiashan/Desktop/website/yimei/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tangjiashan/Desktop/website/yimei/app.config.{js,ts,mjs}"] }));

module.exports = config
